// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_platform_layout from "./routes/(platform)/_layout.tsx";
import * as $_platform_middleware from "./routes/(platform)/_middleware.ts";
import * as $_platform_character_id_ from "./routes/(platform)/character/[id].tsx";
import * as $_platform_characters from "./routes/(platform)/characters.tsx";
import * as $_platform_houses_house_ from "./routes/(platform)/houses/[house].tsx";
import * as $_platform_spells from "./routes/(platform)/spells.tsx";
import * as $_platform_students from "./routes/(platform)/students.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $CharacterFilter from "./islands/CharacterFilter.tsx";
import * as $LogOut from "./islands/LogOut.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(platform)/_layout.tsx": $_platform_layout,
    "./routes/(platform)/_middleware.ts": $_platform_middleware,
    "./routes/(platform)/character/[id].tsx": $_platform_character_id_,
    "./routes/(platform)/characters.tsx": $_platform_characters,
    "./routes/(platform)/houses/[house].tsx": $_platform_houses_house_,
    "./routes/(platform)/spells.tsx": $_platform_spells,
    "./routes/(platform)/students.tsx": $_platform_students,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CharacterFilter.tsx": $CharacterFilter,
    "./islands/LogOut.tsx": $LogOut,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
